
spring:
  datasource:
    url: jdbc:h2:mem:sdw2023
    username: admin
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto:create
    properties:
      hibernate:
        format_aql: true
  h2:
    console:
      enable: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false